name: Android CI
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'
          cache: gradle

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Init gradle wrapper
        run: gradle wrapper

        #- name: Build with Gradle
        #  run: ./gradlew build

        #- name: Build Debug APK
        #  run: ./gradlew assembleDebug

        #- name: Build Release APK
        #  run: ./gradlew assembleRelease

      - name: Build Release
        run: ./gradlew clean build -p demo --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v3.1.1
        with:
          name: ci-builds
          path: demo/build/outputs/
